# Generated by Django 2.2.17 on 2021-04-29 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0006_partnertranslation_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnertranslation',
            name='description',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='description'),
        ),
    ]
