# Generated by Django 2.2.17 on 2021-04-29 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0006_auto_20210416_0313'),
        ('partners', '0007_auto_20210429_2148'),
    ]

    operations = [
    ]
